"""Local Markdown mirror of a project's context.

Writes a grep-able, diff-able, commit-able snapshot to
`<repo_path>/.ctx/context.md` so context is not MCP-only: a tool can read the
file directly (zero tool-call overhead) and MCP is reserved for the write path,
where the deterministic cross-tool merge earns its cost.

Design rules (see CLAUDE.md invariants):
- Best-effort: a failed mirror must NEVER fail or block a context update.
- Never create a repo root that doesn't exist (protects fake-path tests and
  avoids littering phantom dirs) - same existence guard as get_git_summary.
- Atomic write (temp + os.replace) so a concurrent reader never sees a half-file.
"""

import logging
import os
from pathlib import Path
from typing import Optional

from ctx.database import export_project, render_project_markdown, get_project

logger = logging.getLogger("ctx")

_DISABLED_VALUES = {"0", "false", "off", "no"}

_HEADER = (
    "<!-- Generated by one-context (one-ctx). Working memory for this project,\n"
    "     mirrored from ~/.ctx/ctx.db. Safe to commit or .gitignore.\n"
    "     Regenerate with `ctx sync`; disable with CTX_MIRROR=0. Do not hand-edit\n"
    "     (writes are one-way DB -> file and overwrite this). -->\n\n"
)


def mirror_enabled() -> bool:
    """Whether the local file mirror is active (default ON)."""
    if os.environ.get("CTX_DISABLE_MIRROR"):
        return False
    return os.environ.get("CTX_MIRROR", "1").strip().lower() not in _DISABLED_VALUES


def mirror_path(repo_path: str) -> Path:
    """Path of the mirror file for a repo: <repo_path>/.ctx/context.md."""
    return Path(repo_path) / ".ctx" / "context.md"


def write_mirror(project: str, repo_path: Optional[str] = None) -> Optional[str]:
    """Write the project's context snapshot to <repo>/.ctx/context.md.

    Returns the file path on success, or None if mirroring is disabled, the
    project/repo is unavailable, or the repo root doesn't exist. Never raises -
    a mirror failure must not affect the (already-committed) context update.
    """
    if not mirror_enabled():
        return None
    tmp: Optional[Path] = None
    try:
        if not repo_path:
            row = get_project(project)
            if "error" in row:
                return None
            repo_path = row.get("repo_path") or ""
        # Only write under a repo root that already exists - never create one.
        if not repo_path or not Path(repo_path).exists():
            return None

        data = export_project(project)
        if "error" in data:
            return None

        target = mirror_path(repo_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        text = _HEADER + render_project_markdown(data)

        # Atomic: write a sibling temp file, then replace onto the target.
        tmp = target.with_name(f".context.md.{os.getpid()}.tmp")
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, target)
        return str(target)
    except OSError as e:
        logger.debug("mirror write skipped for %s: %s", project, e)
        try:
            if tmp is not None and tmp.exists():
                tmp.unlink()
        except OSError:
            pass
        return None
